service: gtag-identifier

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-plugin-chrome

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**

functions:
  gtag-identifier:
    handler: app.handler
    memorySize: 512 # Set memory size to 512 MB
    timeout: 300 # Set the timeout to 5 minutes (300 seconds)
    events:
      - http:
          path: /identify-gtag
          method: get
          integration: lambda
          integrationTimeout: 300 # Set the integration timeout to 5 minutes (300 seconds)
